"""Modify strings in tasks table

Revision ID: 5773e3d54b78
Revises: e4a9b61072f8
Create Date: 2025-04-14 18:19:04.415163

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5773e3d54b78"
down_revision: Union[str, None] = "e4a9b61072f8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("tasks", "name", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("tasks", "car_id", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("tasks", "status", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("tasks", "status", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("tasks", "car_id", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("tasks", "name", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###
