"""Create messages table

Revision ID: c1591c0bf932
Revises: 5773e3d54b78
Create Date: 2025-04-14 23:54:22.287917

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c1591c0bf932"
down_revision: Union[str, None] = "5773e3d54b78"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "messages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_messages_id"), "messages", ["id"], unique=False)
    op.alter_column("tasks", "name", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("tasks", "car_id", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("tasks", "status", existing_type=sa.VARCHAR(), nullable=False)
    op.drop_column("tasks", "messages")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tasks", sa.Column("messages", sqlite.JSON(), nullable=True))
    op.alter_column("tasks", "status", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("tasks", "car_id", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("tasks", "name", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_index(op.f("ix_messages_id"), table_name="messages")
    op.drop_table("messages")
    # ### end Alembic commands ###
