"""remove indexes for primary_key

Revision ID: 5fda2f091744
Revises: 770301dc1ce9
Create Date: 2025-07-25 16:41:24.886892

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5fda2f091744"
down_revision: Union[str, None] = "770301dc1ce9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_messages_id", table_name="messages")
    op.drop_index("ix_tasks_id", table_name="tasks")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("ix_tasks_id", "tasks", ["id"], unique=False)
    op.create_index("ix_messages_id", "messages", ["id"], unique=False)
    # ### end Alembic commands ###
