"""Add time fields, make messages strings

Revision ID: 770301dc1ce9
Revises: c1591c0bf932
Create Date: 2025-07-25 12:54:41.715780

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "770301dc1ce9"
down_revision: Union[str, None] = "c1591c0bf932"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "messages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("body", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_messages_id"), "messages", ["id"], unique=False)
    op.add_column("tasks", sa.Column("created_at", sa.DateTime(), nullable=False))
    op.add_column("tasks", sa.Column("updated_at", sa.DateTime(), nullable=False))
    op.alter_column("tasks", "name", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("tasks", "car_id", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("tasks", "status", existing_type=sa.VARCHAR(), nullable=False)
    op.drop_column("tasks", "messages")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tasks", sa.Column("messages", sqlite.JSON(), nullable=True))
    op.alter_column("tasks", "status", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("tasks", "car_id", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("tasks", "name", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_column("tasks", "updated_at")
    op.drop_column("tasks", "created_at")
    op.drop_index(op.f("ix_messages_id"), table_name="messages")
    op.drop_table("messages")
    # ### end Alembic commands ###
